#!/bin/bash

set -e

BASE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE:-$0}")"/.. &>/dev/null && pwd)
FILE_PACKAGER="$BASE_DIR/emsdk/upstream/emscripten/tools/file_packager"
FCCACHE_FILE="soffice_fccache.data"
METADATA_SUFFIX=".js.metadata"
FCCAHCE_OUT="$BASE_DIR/libreoffice-core/instdir/program/$FCCACHE_FILE"
QA_ENV_DIR="$BASE_DIR/qa-env"

# Add emscripten toolchain
if [[ "$container" = "podman" ]]; then
  source "/emsdk/emsdk_env.sh"
else
  source "$BASE_DIR/emsdk/emsdk_env.sh"
fi
cd "$BASE_DIR/libreoffice-core"
echo "Building LOK"
make || exit 1
if [ "$GITHUB_ACTIONS" = "true" ]; then
  echo "Skipping FcCache generation"
else
  # Not really, we can do this once and be done with it really
  echo "Generating FcCache"
  cp "$BASE_DIR/$FCCACHE_FILE" "$FCCAHCE_OUT"
  cp "$BASE_DIR/$FCCACHE_FILE$METADATA_SUFFIX" "$FCCAHCE_OUT$METADATA_SUFFIX"
fi
